// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdnxsiiDRs1mPbPb2RXQ_AUIPH-5Bse4',
    appId: '1:321662909954:web:f1b42e297ede6c2c59f11b',
    messagingSenderId: '321662909954',
    projectId: 'digital-islamic-app-2026',
    authDomain: 'digital-islamic-app-2026.firebaseapp.com',
    storageBucket: 'digital-islamic-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSexL8U0lQlwUrlTwYzSgaxF35aIOKECw',
    appId: '1:321662909954:android:868e04401f1eb7b559f11b',
    messagingSenderId: '321662909954',
    projectId: 'digital-islamic-app-2026',
    storageBucket: 'digital-islamic-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpahZwmV-Y1HrlS3qma8CSU0lPi3MbsR0',
    appId: '1:321662909954:ios:d85aa6f08f915c7359f11b',
    messagingSenderId: '321662909954',
    projectId: 'digital-islamic-app-2026',
    storageBucket: 'digital-islamic-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.digitalIslamicHub',
  );
}
